In [2]:
import numpy as np 

In [18]:
cov=np.zeros([3,3])
cov[0,:]=[100,25,0]
cov[1,:]=[25,400,0]
cov[2,:]=[0,0,.16]
y=np.array([1/np.sqrt(cov[i,i]) for i in range(cov.shape[0])])


In [19]:
cov_y=cov.copy()
for i in range(cov.shape[0]):
    for j in range(cov.shape[1]):
        cov_y[i,j]=cov_y[i,j]*y[i]*y[j]
cov_y

array([[1.   , 0.125, 0.   ],
       [0.125, 1.   , 0.   ],
       [0.   , 0.   , 1.   ]])

In [34]:
y_prime=np.ones((3,1))
# y_prime[:,0]=[1,2,3]
normalize= lambda  y_prime: y_prime/np.linalg.norm(y_prime)
y=normalize(y_prime)
y.T@cov_y@y

array([[1.08333333]])

In [49]:
k=2
eig_vals, eig_vectors=np.linalg.eig(cov_y)
print(eig_vals)
print(eig_vectors)
index=np.argsort(eig_vals)[eig_vals.shape[0] -k :]
print(index)
principal_directions=eig_vectors[:, index]
print(principal_directions)

[1.125 0.875 1.   ]
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
[2 0]
[[0.         0.70710678]
 [0.         0.70710678]
 [1.         0.        ]]
